name: Generate docs
on:
  push:
    branches:
      - main

jobs:
  generate_docs:
    runs-on: [ubuntu-20.04]
    steps:
      - uses: actions/checkout@v4
    
      - uses: actions/checkout@v4
        with:
          repo: paulfermoreyes/mkdocs-sub1
          path: sub1

      - uses: actions/checkout@v4
        with:
          repo: paulfermoreyes/mkdocs-sub2
          path: sub2

      - run: ls -la
      
